### ISSUE TITLE
question about save result img 

### ISSUE THREAD

**Issue by HymEric** [LoSealL/VideoSuperResolution#34]
Do you do `clip(0,255)` about the output HR- img by vespcn model?
Could you tell me which file line do you save output of model?

**Comment by LoSealL** [comment]
Yeah, I clip the value.
The saving function is in `Callbacks.py`, the `save_image` function.

**Comment by HymEric** [comment]
Cool. And I want to ask if I want to calculate the mean/average time in test or infer stage. What can I do ?
Where can I to insert python `time.time() `?

**Comment by LoSealL** [comment]
I don't recommend to measure time because pytorch is not optimized for inference speed, compare just a **time** is meaningless. However, if you insist:
- the progress bar of `tqdm` has already shown running time, you can easily get average time;
- The core execution of TF is in `VSR/Tools/Run.py` and PyTorch is in `VSRTorch/eval.py`. You may insert before and after `t.infer` or `t.benchmark`.

**Comment by HymEric** [comment]
Thanks for your recommendation.
