### ISSUE TITLE
Issue with Eval of VESPCN  in VSRTorch.

### ISSUE THREAD

**Issue by AIRedWood** [LoSealL/VideoSuperResolution#68]
Hello, I trained vespcn with VSRtorch and tested it, but the results of the test are not ideal, psnr is only 23.50. I have considered several reasons:
1. There is no test only on the Y channel (this problem occurs when I use VSR for testing, do not use --l_only, psnr=23.**, use --l_only, psnr=25.**) I view The parameters of VSRtorch found --output_color. But when I use --output_color RGB and --output_color GRAY , psnr doesn't change at all, it's 23.50. Excuse me, where is it wrong?
2. When I use the vid4 dataset to test it in the VSR. The progress shows 1, 2, ..., 163/163. But in VSRtorch. The progress shows 1, 2, ..., 171/171. (vid4 is four groups of videos, a total of 171 pictures, considering taking the first frame and the last frame, the picture participating in eval should be 163), I would like to ask if this is a display problem or indeed VSRTORch does not consider the interframe Align

**Comment by LoSealL** [comment]
1 The psnr print after testing is the same, because it get psnr on directly output and the model always output 1 channel image.
When you choose output RGB, the other 2 channel is bicubical resized to target resolution.

PSNR on luminance channel is always better and because of historical reason, we always compare on that channel.

 2. Maybe I forget to pad head and tail frames in VSR, I will check and fix that.

**Comment by LoSealL** [comment]
I have tested with the latest commit:
 `python run.py --model vespcn --test vid4` and `python run.py --model vespcn --infer /data/vid4/input` all show progress 1..171/171.
