### ISSUE TITLE
Loading specific paths for TecoGAN

### ISSUE THREAD

**Issue by SandLeg** [LoSealL/VideoSuperResolution#71]
So I am trying to run eval.py on my TecoGAN model but there are two .pth files for every path. Whenever I try to load the gnet for example the dnet wont load. I have been trying to find a work around without changing the source code but nothing has worked so far.

**Comment by LoSealL** [comment]
If you'd like to specify a weight file to run for evaluation, you just need **gnet**, because **dnet** the discriminator won't be used at inference.

Or if you want to check the intermediate output with your trained weights, you can use `--epoch=100` instead of using `--pth=../Results/tecogan/save/gnet_epoch0100.pth`
